"""Monkey patches for ArgumentParser.

In order to support Python 3.7 and 3.8 while retaining the tests, we need to
backport the bugfix for [BPO-29298].

[BPO-29298]: https://bugs.python.org/issue29298
"""

# Standard
import argparse
import sys

# Typing
from typing import Optional


# In Python pre-3.9, argparse fails with required subparsers, unnamed dest, and
# empty argv. The bug BPO-29298 was fixed in 3.11 and backported to 3.10 and 3.9
# Here, we backport it to 3.7 and 3.8 as well, via monkey-patching
# https://github.com/python/cpython/blob/v3.11.1/Lib/argparse.py#L739-L751
if sys.version_info < (3, 9):  # pragma: <3.9 cover
    def _get_action_name(argument: Optional[argparse.Action]) -> Optional[str]:  # pragma: no cover
        """Returns the action name for an argument action.

        For arguments with option strings, it concatenates those with a slash.
        For arguments with `metavar` or `dest`, it returns those. For arguments
        with `choices`, it returns the list of those.

        Args:
            argument (Optional[argparse.Action]): Action generated by the argument.

        Returns:
            Optional[str]: Derived action name
        """
        if argument is None:
            return None
        elif argument.option_strings:
            return '/'.join(argument.option_strings)
        elif argument.metavar not in (None, argparse.SUPPRESS):
            return argument.metavar
        elif argument.dest not in (None, argparse.SUPPRESS):
            return argument.dest
        elif argument.choices:
            return '{' + ','.join(argument.choices) + '}'
        else:
            return None

    # Monkey-Patch
    argparse._get_action_name = _get_action_name
