name: Lint

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * 0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Set Hatch Python Version
        run: echo "HATCH_PYTHON=${{ steps.setup-python.outputs.python-path }}" >> $GITHUB_ENV
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-3.12-${{ hashFiles('pyproject.toml') }}
      - name: Install Hatch
        uses: pypa/hatch@install
      - name: Run Build Hooks
        run: hatch build --hooks-only
      - name: Run Lint
        run: hatch run lint
