name: Linting

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Hatch
        run: pipx install hatch
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: pip
      - name: Run Linting
        run: hatch run lint
