name: Linting

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Setup UV
        uses: yezz123/setup-uv@v4
        with:
          uv-venv: .venv
      - name: Install Dependencies
        run: uv pip install  -e . -r pyproject.toml --extra=dev --extra=docs
      - name: Run Linting
        run: poe lint
