name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"

jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-13", "windows-latest" ]
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]
      fail-fast: false
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup UV
        uses: yezz123/setup-uv@v4
        with:
          uv-venv: .venv
      - name: Install Dependencies
        run: uv pip install  -e . -r pyproject.toml --extra=dev --extra=docs
      - name: Run Tests
        run: |
          poe test
          coverage lcov
      - name: Coverage Results
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
          flag-name: ${{ matrix.os }}-${{ matrix.python-version }}
          parallel: true

  coverage:
    name: Coverage
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
