name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * 0

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]
        pydantic-version: [ "1.0", "2.0" ]
      fail-fast: false
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Set Hatch Python Version
        run: echo "HATCH_PYTHON=${{ steps.setup-python.outputs.python-path }}" >> $GITHUB_ENV
      - name: Install Hatch
        uses: pypa/hatch@install
      - name: Install Pydantic
        run: hatch run uv pip install pydantic~=${{ matrix.pydantic-version }}
      - name: Run Build Hooks
        run: hatch build --hooks-only
      - name: Run Tests
        run: hatch run test && hatch run coverage xml
      - name: Coverage Results
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
