name: Type

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *

jobs:
  type:
    name: Type
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup Hatch Environment Variables
        run: echo "HATCH_PYTHON=${{ steps.setup-python.outputs.python-path }}" >> $GITHUB_ENV
      - name: Install Hatch
        uses: pypa/hatch@install
      - name: Run Build Hooks
        run: hatch build --hooks-only
      - name: Run Type Checking
        run: hatch run type
