name: Typing

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"

jobs:
  typing:
    name: Typing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: pip
      - name: Install Hatch
        run: python -m pip install hatch
      - name: Run Type Checking
        run: hatch run type
